insert into ingredients (id, name ) values
    (1, 'Potato'),
    (2, 'Tomato'),
    (3, 'Onion'),
    (4, 'Garlic'),
    (5, 'Capsicum'),
    (6, 'Cheese'),
    (7, 'Rice Flour'),
    (8, 'Wheat Flour'),
    (9, 'Broccoli'),
    (10, 'Green Chilly'),
    (11, 'Fish'),
    (12, 'Mutton'),
    (13, 'Pork'),
    (14, 'Salmon'),
    (15, 'Tuna'),
    (16, 'Barley'),
    (17, 'Soybean Oil'),
    (18, 'Mustard Oil'),
    (19, 'Sunflower Oil'),
    (20, 'Egg'),
    (21, 'Sugar');

